# Generated by Django 4.2.3 on 2023-09-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_appuser_is_staff_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='modified_by',
        ),
    ]
